apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\bubth\go\bin\kompose.exe --file .\docker-compose.yml convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kbk
  name: kbk
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kbk
    spec:
      containers:
      - image: kbk
        name: kbk
        ports:
        - containerPort: 3306
        - containerPort: 8989
        resources: {}
      restartPolicy: Always
status: {}
