apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kbk-player-pvc
spec:
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kbk-sys-pvc
spec:
  storageClassName: hostpath

