apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-local

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: local

patchesStrategicMerge:
  - kbk-configmap.yaml
  - kbk-pvc-patch.yaml

