apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-staging

resources:
  - namespace.yaml
  - ../../base

# Add namespace to all resources
commonLabels:
  environment: staging

# Patch ingress to use staging hostname
patchesStrategicMerge:
  - ingress-patch.yaml

