# ClusterIP service for both HTTP Ingress and TCP routing via ingress-nginx
apiVersion: v1
kind: Service
metadata:
  name: kbk-service
spec:
  type: ClusterIP
  selector:
    app: kbk
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      name: telnet
    - protocol: TCP
      port: 80
      targetPort: 8989
      name: http

