apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass-retain.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - kbk-deployment.yaml
  - kbk-pvc.yaml
  - kbk-service-http.yaml
  - kbk-ingress.yaml

