apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    tilt.dev/down-policy: keep
  name: mysql-pvc
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

