apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-dev

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: dev

commonAnnotations:
  deployed-branch: knights-rule
  deployed-sha: 313de19

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: bubthegreat/kbk
    newTag: knights-rule-313de19
