apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-dev

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: dev
  branch: help-commands

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: bubthegreat/kbk
    newTag: help-commands-6ad9c61
  - name: bubthegreat/kbk-sql
    newTag: help-commands-6ad9c61
