apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-dev

resources:
  - namespace.yaml
  - ../../base

# Add namespace to all resources
commonLabels:
  environment: dev

# Patch ingress to use dev hostnames
patchesStrategicMerge:
  - ingress-patch.yaml

