apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-dev

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: dev

commonAnnotations:
  deployed-branch: color-coded-room-names
  deployed-sha: 77d70d0

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: bubthegreat/kbk
    newTag: color-coded-room-names-77d70d0
  - name: bubthegreat/kbk-sql
    newTag: color-coded-room-names-77d70d0
