apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-dev

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: dev

commonAnnotations:
  deployed-branch: compiler-fixes
  deployed-sha: 850d5e5

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: bubthegreat/kbk
    newTag: compiler-fixes-850d5e5
