apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kbk-service
  name: kbk-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kbk-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/kbk-network: "true"
        io.kompose.service: kbk-service
    spec:
      containers:
        - image: kbk-service
          name: kbk-service
          ports:
            - containerPort: 8989
          resources: {}    
          volumeMounts:
            - mountPath: /kbk/test
              name: areamount
      volumes:
        - name: areamount
          hostPath:
            path: /home/bub/Development/kbk/area
          restartPolicy: Always
status: {}
